import { vi } from './vi';

export const en: typeof vi = {
  nav: {
    about: 'ABOUT US',
    curriculum: 'COURSES',
    news: 'NEWS & EVENTS',
    faq: 'FAQ',
    careers: 'CAREERS',
    contact: 'CONTACT',
    welcome: 'Welcome',
    logout: 'Logout',
  },
  footer: {
    copyright: 'THIEUNAM iCAM ©',
    allRightsReserved: 'All rights reserved by ICANCAM.',
  },
  shortcuts: {
    zalo: 'Chat Zalo',
    messenger: 'Chat Messenger',
    email: 'Send Email',
  },
  home: {
    registerNow: 'REGISTER NOW',
    newsOverviewLabel: 'NEWS & EVENTS OVERVIEW',
    achievementsLabel: 'ICAM KEY ACHIEVEMENTS',
    yearsExp: '10 years',
    yearsExpDesc: 'English training experience',
    cambridgeShields: '15/15 shields',
    cambridgeShieldsDesc: 'Cambridge Starters, Movers & Flyers certificates',
    studentsCount: '10,000+',
    studentsCountDesc: 'trusted students in Hoc Mon & District 12',
    teachersCount: '100%',
    teachersCountDesc: 'native & Vietnamese teachers with TESOL / CELTA',
    iSMARTLabel: '21ST CENTURY ONLINE EDUCATION SYSTEM',
    iSMARTTitle: 'iCAM ONLINE — UNLIMITED LEARNING WITH HOLOGRAM & SMARTBOARD TECH',
    iSMARTDesc: 'Modern online English learning combining Smartboard interactive screens, British curriculum, and Hologram technology for visual absorption.',
    teachersLabel: 'EXPERT NATIVE & VIETNAMESE FACULTY TEAM',
    studentsLabel: 'OUTSTANDING STUDENTS STUDYING AT ICAM',
    parentsLabel: 'FEEDBACK FROM ICAM PARENTS',
    regTitle: 'Book Free 4-Skill Assessment & Consultation',
    regDesc: 'Fill out the form below and an ICANCAM academic specialist will contact you to tailor the best learning pathway for your child.',
    regNameLabel: 'Parent / Student Full Name *',
    regNamePlaceholder: 'Enter full name...',
    regPhoneLabel: 'Contact Phone Number *',
    regPhonePlaceholder: 'Enter phone number...',
    regEmailLabel: 'Email Address',
    regEmailPlaceholder: 'email@example.com...',
    regAgeLabel: 'Student Age *',
    regAgePlaceholder: 'e.g. 6 years old, 12 years old...',
    regCampusLabel: 'Preferred Campus *',
    regCampusHocMon: 'Hoc Mon & District 12 Campus (344 A To 13 KP 1, Trung My Tay)',
    regSubmitBtn: 'Register For Free Consultation',
  },
  about: {
    heroBadge: 'ICANCAM — HOC MON & DISTRICT 12',
    heroTitle: '21st Century English Education Model',
    heroTagline: 'Confident Communication • Independent Learning • Language Mastery',
    heroDesc: 'ICANCAM pioneers modern education, combining 4Ls and LETI methodologies so students not only learn English but actively master it for a lifetime.',
    exploreBtn: 'Explore Our Method',
    consultBtn: 'Book Consultation',
    campusHocMon: 'Hoc Mon Campus',
    campusQ12: 'District 12 Campus',
    missionTag: 'MISSION DECLARATIONS',
    missionTitle: 'Unlocking Independent Learning Potential',
    missionSubtitle: 'Our mission goes beyond delivering knowledge—we empower students to become confident, independent English users with lifelong self-learning capabilities.',
    dec1Title: 'Declaration 1',
    dec1Decl: 'I can communicate in English.',
    dec1Sub: 'I can communicate in English with confidence.',
    dec1Desc: 'Break hesitation barriers and build natural speech reflexes in a 100% English environment.',
    dec2Title: 'Declaration 2',
    dec2Decl: 'I can master English.',
    dec2Sub: 'I can master English fully.',
    dec2Desc: 'Master Listening, Speaking, Reading, Writing and apply skills fluently to academics and daily life.',
    dec3Title: 'Declaration 3',
    dec3Decl: 'I can learn English independently.',
    dec3Sub: 'I can learn English independently.',
    dec3Desc: 'Equip self-research methods and critical thinking to become lifelong active learners.',
    valuesTag: 'CORE VALUES',
    valuesTitle: '4 Capability Pillars at ICANCAM',
    val1Title: 'Confident Communication',
    val1Desc: 'Express ideas fluently and debate naturally in English.',
    val2Title: 'Independent Learning',
    val2Desc: 'Build enduring self-research habits and methodologies.',
    val3Title: 'Language Mastery',
    val3Desc: 'Develop comprehensive 4Ls skills for academic & practical success.',
    val4Title: 'Sustainable Growth',
    val4Desc: 'Foster critical thinking and global citizen poise.',
    compTag: 'WHY CHOOSE US',
    compTitle: 'Comparing English Education Models',
    toggleTrad: 'Traditional Approach',
    toggleCAM: 'ICANCAM (21st Century)',
    tradHeader: 'Passive Traditional Approach',
    trad1: 'Rote grammar memorization with limited speaking opportunities',
    trad2: 'Focus on short-term exam prep, easily forgotten after courses',
    trad3: 'Lack of confidence and hesitation speaking with native speakers',
    trad4: 'Total dependence on teachers without independent study skills',
    camHeader: 'ICANCAM 21st Interactive Model',
    cam1: '80% interactive practice time using 4Ls + LETI methodology',
    cam2: 'Vibrant Smartboard classroom with accredited British curriculum',
    cam3: 'Natural speech reflexes and public speaking confidence',
    cam4: 'Lifelong independent learning mastery',
    methodTag: 'TEACHING METHODOLOGY',
    methodTitle: 'Combining 4Ls & LETI Frameworks',
    methodDesc: 'Exclusive educational framework optimizing language acquisition and active reflexes.',
    tab4Ls: '4Ls Framework (4 Core Skills)',
    tabLETI: 'LETI Method (Two-way Interaction)',
    lsListening: 'Listening',
    lsListeningDesc: 'Immersive listening with native audio & British educational software.',
    lsSpeaking: 'Speaking',
    lsSpeakingDesc: 'Natural speech reflexes with IPA pronunciation from day one.',
    lsReading: 'Reading',
    lsReadingDesc: 'Text comprehension and rich academic vocabulary expansion.',
    lsWriting: 'Writing',
    lsWritingDesc: 'Essay writing skills, logical structure, and articulate expression.',
    classTag: '21ST CENTURY FACILITIES',
    classTitle: '21st Century Smart Classrooms',
    classDesc: 'Modern tech infrastructure offering maximal support for interactive learning.',
    class1Title: 'Smartboard Touchscreens',
    class1Desc: '100% of rooms feature direct interactive touchscreens.',
    class2Title: 'Accredited British Software',
    class2Desc: 'Curriculum & software certified by leading publishing houses.',
    class3Title: 'Multimedia Learning',
    class3Desc: '3D imagery and vivid video making lessons memorable.',
    class4Title: '100% English Environment',
    class4Desc: 'Immersive language space triggering natural speech reflexes.',
    journeyTag: 'STUDENT DEVELOPMENT',
    journeyTitle: 'Student Capability Journey',
    jStep1Title: '1. Discovery',
    jStep1Desc: 'Ignite passion and build solid Phonics foundation.',
    jStep2Title: '2. Interaction',
    jStep2Desc: 'Practice two-way speech reflexes via LETI framework.',
    jStep3Title: '3. Mastery',
    jStep3Desc: 'Master 4Ls and confidently achieve international certificates.',
    jStep4Title: '4. Independent Learning',
    jStep4Desc: 'Own lifelong self-research and study methodologies.',
    outcomesTag: 'STUDENT OUTCOMES',
    outcomesTitle: 'Results Achieved After Course Completion',
    out1: 'Natural and confident English communication with native speakers',
    out2: 'Proficiency in 4Ls (Listening, Speaking, Reading, Writing) to academic standards',
    out3: 'Mastery of independent learning and critical thinking skills',
    out4: 'Top scores in Cambridge and IELTS examinations',
    out5: 'Effective public presentation and teamwork skills',
    out6: 'Ready to integrate as global citizens',
    storyBadge: 'QUALITY COMMITMENT TO HOC MON & DISTRICT 12',
    storyTitle: 'Bringing 21st Century Education to Hoc Mon & District 12',
    storyP1: 'ICANCAM was established with the vision of bringing international 21st-century English education standards to parents and students in Hoc Mon and District 12, Ho Chi Minh City.',
    storyP2: 'We believe every student has boundless language potential when empowered in a modern interactive environment, guided by 4Ls + LETI methods, and inspired to learn independently.',
    ctaTitle: 'Ready to Master English with ICANCAM?',
    ctaDesc: 'Book today to receive a personalized learning roadmap and schedule a free 4-skill assessment.',
    ctaPrimaryBtn: 'Book Consultation Now',
    ctaSecondaryBtn: 'View All Courses',
  },
  curriculum: {
    heroBadge: 'INTERNATIONAL STANDARD CURRICULUM',
    heroTitle: 'ICANCAM Training Programs',
    heroSubtitle: 'Optimal learning pathways combining 4Ls + LETI models and 21st-century technology for 4-skill mastery and lifelong independent study.',
    filterAll: 'All Programs',
    filterKids: 'Kids & Primary (4-11y)',
    filterTeens: 'Teens (12-15y)',
    filterIelts: 'IELTS Preparation',
    filterComm: 'Practical Communication',
    filterOnline: 'iCAM Online',
    durationLabel: 'Duration:',
    targetGroupLabel: 'Target Group:',
    commitmentLabel: 'Outcome Target:',
    viewSyllabusBtn: 'View Syllabus Details',
    registerBtn: 'Book Consultation',
    whyTag: 'KEY ADVANTAGES',
    whyTitle: 'Why Are ICANCAM Pathways So Effective?',
    ctaTitle: 'Unsure Which Course Fits Your Child?',
    ctaDesc: 'Book a free English proficiency test and receive a personalized learning roadmap from ICANCAM experts today.',
    ctaPrimaryBtn: 'Book Free Placement Test',
    ctaSecondaryBtn: 'Call Consultation Hotline',
  },
  contact: {
    heroBadge: 'ICANCAM — HOC MON & DISTRICT 12',
    heroTitle: 'Contact Us & Book Consultation',
    heroSubtitle: 'Reach out to receive a personalized learning roadmap and book a 100% free 4-skill proficiency assessment with ICANCAM experts.',
    hotlineBadge: 'Hotline: 0909 123 456',
    hoursBadge: 'Mon - Sun: 08:00 - 21:30',
    campusTitle: 'ICANCAM Headquarters',
    subTag: 'Hoc Mon & District 12',
    addressLabel: 'Official Address:',
    hotlineLabel: 'Admissions & Support Hotline:',
    emailLabel: 'Support Email:',
    mapsBtn: 'Directions on Google Maps',
    hoursTitle: 'Center Operating Hours',
    hoursDesc: 'Monday – Sunday | 08:00 – 21:30 (Open 7 days a week)',
    commitTitle: 'Consultation Commitment',
    commitDesc: 'Advisors reply within 24h & Free 4-skill placement test 100%.',
    formTitle: 'Book Consultation & Placement Test',
    formDesc: 'Students receive a free 4-skill assessment and personalized roadmap.',
    successAlert: 'Request submitted! ICANCAM advisors will contact you within 24 hours.',
    fullNameLabel: 'Full Name *',
    phoneLabel: 'Phone Number *',
    emailInputLabel: 'Email Address',
    branchLabel: 'Preferred Campus *',
    branchOpt1: 'Trung My Tay Campus (344 A To 13 KP 1, HCMC)',
    branchOpt2: 'Hoc Mon & District 12 Campus',
    courseLabel: 'Interested Course *',
    messageLabel: 'Message / Additional Requests',
    submitBtn: 'Submit Consultation Request',
    mapTitle: 'ICANCAM Map Location',
    openAppBtn: 'Open Google Maps App',
  },
};

