import { vi } from './vi';

export const en: typeof vi = {
  nav: {
    about: 'ABOUT US',
    curriculum: 'COURSES',
    news: 'NEWS & EVENTS',
    faq: 'FAQ',
    careers: 'CAREERS',
    contact: 'CONTACT',
    welcome: 'Welcome',
    logout: 'Logout',
  },
  footer: {
    copyright: 'THIEUNAM iCANCAM ©',
    allRightsReserved: 'All rights reserved by iCANCAM.',
  },
  shortcuts: {
    scrollTop: 'Back to Top',
    zalo: 'Chat Zalo',
    messenger: 'Chat Messenger',
    email: 'Send Email',
  },
  home: {
    registerNow: 'REGISTER NOW',
    newsOverviewLabel: 'NEWS & EVENTS OVERVIEW',
    achievementsLabel: 'iCANCAM KEY ACHIEVEMENTS',
    yearsExp: '10 years',
    yearsExpDesc: 'English training experience',
    cambridgeShields: '15/15 shields',
    cambridgeShieldsDesc: 'Cambridge Starters, Movers & Flyers certificates',
    studentsCount: '10,000+',
    studentsCountDesc: 'trusted students in Hoc Mon & District 12',
    teachersCount: '100%',
    teachersCountDesc: 'native & Vietnamese teachers with TESOL / CELTA',
    iSMARTLabel: '21ST CENTURY ONLINE EDUCATION SYSTEM',
    iSMARTTitle: 'iCANCAM ONLINE — UNLIMITED LEARNING WITH HOLOGRAM & SMARTBOARD TECH',
    iSMARTDesc: 'Modern online English learning combining Smartboard interactive screens, British curriculum, and Hologram technology for visual absorption.',
    teachersLabel: 'EXPERT NATIVE & VIETNAMESE FACULTY TEAM',
    studentsLabel: 'OUTSTANDING STUDENTS STUDYING AT iCANCAM',
    parentsLabel: 'FEEDBACK FROM iCANCAM PARENTS',
    regTitle: 'Book Free 4-Skill Assessment & Consultation',
    regDesc: 'Fill out the form below and an iCANCAM academic specialist will contact you to tailor the best learning pathway for your child.',
    regNameLabel: 'Parent / Student Full Name *',
    regNamePlaceholder: 'Enter full name...',
    regPhoneLabel: 'Contact Phone Number *',
    regPhonePlaceholder: 'Enter phone number...',
    regEmailLabel: 'Email Address',
    regEmailPlaceholder: 'email@example.com...',
    regAgeLabel: 'Student Age *',
    regAgePlaceholder: 'e.g. 6 years old, 12 years old...',
    regCampusLabel: 'Preferred Campus *',
    regCampusHocMon: 'Hoc Mon & District 12 Campus (344 A To 13 KP 1, Trung My Tay)',
    regSubmitBtn: 'Register For Free Consultation',
  },
  about: {
    heroBadge: 'iCANCAM — HOC MON & DISTRICT 12',
    heroTitlePrefix: '21st Century English ',
    heroTitleHighlight: 'Educational Model',
    heroTagline: 'Confident Communication • Independent Learning • Language Mastery',
    heroDescription: 'iCANCAM pioneers modern educational models combining 4Ls and LETI methodologies so students not only learn English but actively master and self-study for life.',
    exploreMethodBtn: 'Explore Methodologies',
    registerBtn: 'Book Consultation',
    missionTag: 'iCANCAM MISSION',
    missionTitlePrefix: 'Unlocking Independent ',
    missionTitleHighlight: 'Self-Study Skills',
    missionSubtitle: 'iCANCAM\'s mission goes beyond transferring knowledge—it is accompanying students to become confident, independent English users capable of lifelong self-growth.',
    declaration1Sub: 'I can communicate in English confidently',
    declaration1Desc: 'Express ideas boldly, communicate naturally without barriers in all daily life situations.',
    declaration2Sub: 'I can master English',
    declaration2Desc: 'Master all 4 core skills (Listening, Speaking, Reading, Writing) and flexibly apply English to personal goals.',
    declaration3Sub: 'I can learn English independently',
    declaration3Desc: 'Possess effective self-study methods, capable of researching and expanding language knowledge independently.',
    valuesTag: 'CORE VALUES',
    valuesTitle: '4 Pillars of Student Capability',
    val1Title: 'Confident Communication',
    val1Desc: 'Eliminate hesitation, helping students proactively ask questions, discuss, and express views in English.',
    val2Title: 'Independent Self-Study',
    val2Desc: 'Equip research mindsets, enabling students to access new knowledge proactively without dependency.',
    val3Title: 'Language Mastery',
    val3Desc: 'Deeply understand language nature to use it naturally as a thinking tool rather than passive memorization.',
    val4Title: 'Sustainable Growth',
    val4Desc: 'Establish solid foundations for students to continue self-learning and advancing throughout their future journey.',
    whyTag: 'THE DIFFERENCE',
    whyTitle: 'Interactive Learning Over Passive Memorization',
    whySubtitle: 'iCANCAM replaces rote learning with interactive environments and real-world application.',
    tabTraditional: 'Traditional Learning',
    tabCam: 'iCANCAM Model ★',
    tradHeaderTitle: 'Traditional English Learning',
    tradHeaderBadge: 'Passive Memorization',
    tradItem1: 'Rote memorization of dry vocabulary lists and grammar formulas.',
    tradItem2: 'One-way lectures with minimal conversational practice.',
    tradItem3: 'Studying just to pass exams, lacking real-life application.',
    tradItem4: 'Passive reliance on teachers with no self-learning strategy.',
    camHeaderTitle: 'iCANCAM Methodology',
    camHeaderBadge: '4Ls + LETI Interactive',
    camItem1: 'Learn via interaction, group discussion, and scenario experience.',
    camItem2: '100% English immersion triggering natural speech reflexes.',
    camItem3: 'Cultivate critical thinking, teamwork, and problem-solving skills.',
    camItem4: 'Form independent self-learning habits for lifelong knowledge retention.',
    methodTag: 'TEACHING METHODOLOGY',
    methodTitlePrefix: 'Breakthrough Synergy: ',
    methodTitleHighlight: '4Ls & LETI',
    methodSubtitle: 'A 21st-century English education model combining 4 core language skills with interactive learning.',
    tab4Ls: '4Ls Model (Core Skills)',
    tabLeti: 'LETI Method (Interactive)',
    ls1Title: 'Listening',
    ls1Desc: 'Practice listening across diverse accents, active comprehension, and quick reflexes.',
    ls2Title: 'Speaking',
    ls2Desc: 'Accurate pronunciation, fluent expression of ideas, and public speaking confidence.',
    ls3Title: 'Reading',
    ls3Desc: 'In-depth text comprehension, context analysis, and rich vocabulary accumulation.',
    ls4Title: 'Writing',
    ls4Desc: 'Logical thinking, coherent sentence structures, and effective written expression.',
    letiBannerTitle: 'LETI — Learning English Through Interactions',
    letiBannerSub: 'Learn English Through Direct Interaction & Diverse Practical Experiences',
    letiItem1Title: 'Interaction',
    letiItem1Desc: 'Continuous two-way interaction between teachers and students in class.',
    letiItem2Title: 'Communication',
    letiItem2Desc: 'Practice exchanging and presenting views in natural English.',
    letiItem3Title: 'Application',
    letiItem3Desc: 'Apply learned knowledge to solve real-world challenges.',
    letiItem4Title: 'Discussion',
    letiItem4Desc: 'Group discussions developing critical thinking and teamwork.',
    letiItem5Title: 'Practice',
    letiItem5Desc: 'Continuous practice through scenario tasks and learning projects.',
    letiItem6Title: 'Real-Life Activities',
    letiItem6Desc: 'Experience language in genuine communicative environments.',
    classroomTag: 'LEARNING ENVIRONMENT',
    classroomTitle: '21st Century Smart Classrooms',
    classroomSubtitle: 'Modern tech-integrated learning spaces delivering vivid visual interactive experiences.',
    class1Title: 'Interactive Smartboards',
    class1Desc: 'Smart Interactive Boards make lessons engaging, allowing students to directly touch and interact with content.',
    class2Title: 'British Educational Software',
    class2Desc: 'International-standard British educational software providing diverse, rich, and highly interactive learning resources.',
    class3Title: 'Multimedia Learning',
    class3Desc: 'Multimedia & tech-enhanced learning combining images, audio, and tools to maximize memory retention.',
    class4Title: '100% English Environment',
    class4Desc: '100% English-speaking environment creating a complete language bath, triggering natural reflexes.',
    journeyTag: 'STUDENT JOURNEY',
    journeyTitle: '4 Steps to Language Competency Development',
    step1Title: 'Unlocking & Exposure',
    step1Desc: 'Exposure to 100% English environment and access to LETI interactive learning methods.',
    step2Title: 'Interaction & Communication',
    step2Desc: 'Continuous 4Ls practice through group discussion, practical activities, and two-way feedback.',
    step3Title: 'Confidence & Mastery',
    step3Desc: 'Forming natural reflexes, confidently presenting ideas, and mastering all 4 English skills.',
    step4Title: 'Independent Self-Study',
    step4Desc: 'Mastering self-study methods, maintaining and expanding knowledge independently for life.',
    outcomesTag: 'VALUES GAINED',
    outcomesTitle: '6 Comprehensive Capabilities Post-Course',
    out1Title: 'Confidence',
    out1Desc: 'Boldly expressing oneself and communicating naturally.',
    out2Title: 'Communication Skills',
    out2Desc: 'Expressing thoughts clearly and listening empathetically.',
    out3Title: 'Independent Learning Ability',
    out3Desc: 'Proactively exploring and developing knowledge independently.',
    out4Title: 'Critical Thinking',
    out4Desc: 'Analyzing information and solving problems logically.',
    out5Title: 'Practical English',
    out5Desc: 'Applying English effectively in real life and academics.',
    out6Title: 'Global Mindset',
    out6Desc: 'Ready for international integration and global connection.',
    storyTag: 'INNOVATION JOURNEY',
    storyTitle: 'Pioneering Education in Hoc Mon & District 12',
    storyP1: 'With cumulative expertise in English teaching, iCANCAM constantly researches and innovates to bring pioneering 21st-century education models to students in Hoc Mon and District 12.',
    storyP2: 'We believe every student holds immense potential to become a fluent and independent English user. Combining 4Ls + LETI with smart classroom technology, iCANCAM is committed to building the most inspiring learning environment.',
    ctaTitle: 'Ready to Master English with iCANCAM?',
    ctaDesc: 'Let your child experience modern education, activate independent self-study skills, and communicate confidently today.',
    ctaPrimaryBtn: 'Book Consultation Now',
    ctaSecondaryBtn: 'View Courses & Pathways',
  },
  curriculum: {
    heroBadge: 'INTERNATIONAL STANDARD CURRICULUM',
    heroTitle: 'iCANCAM Training Programs',
    heroSubtitle: 'Optimal learning pathways combining 4Ls + LETI models and 21st-century technology for 4-skill mastery and lifelong independent study.',
    filterAll: 'All Programs',
    filterKids: 'Kids & Primary (4-11y)',
    filterTeens: 'Teens (12-15y)',
    filterIelts: 'IELTS Preparation',
    filterComm: 'Practical Communication',
    filterOnline: 'iCAM Online',
    durationLabel: 'Duration:',
    targetGroupLabel: 'Target Group:',
    commitmentLabel: 'Outcome Target:',
    viewSyllabusBtn: 'View Syllabus Details',
    registerBtn: 'Book Consultation',
    whyTag: 'EXCELLENT ADVANTAGES',
    whyTitle: 'Why Are iCANCAM Pathways So Effective?',
    whyCard1Title: 'Interactive 4Ls + LETI Model',
    whyCard1Desc: 'Combining 4 core skills with two-way interaction, discussions, and practical activities.',
    whyCard2Title: '21st Century Smart Classroom',
    whyCard2Desc: 'Equipped with Smartboards, British curriculum, and visual multimedia technology.',
    whyCard3Title: 'Clear Outcome Commitment',
    whyCard3Desc: 'Personalized step-by-step roadmaps, regular progress tracking, and written guarantees.',
    whyCard4Title: 'Unlocking Self-Learning Ability',
    whyCard4Desc: 'Empowering students to master independent research for lifelong intellectual growth.',
    modalSyllabusTitle: 'Detailed Training Syllabus',
    modalRegisterBtn: 'Book Suitable Course Consultation',
    ctaTitle: 'Unsure Which Course Fits Your Child?',
    ctaDesc: 'Book a free English proficiency test and receive a personalized learning roadmap from iCANCAM experts today.',
    ctaPrimaryBtn: 'Book Free Placement Test',
    ctaSecondaryBtn: 'Call Consultation Hotline',
  },
  contact: {
    heroBadge: 'iCANCAM — HOC MON & DISTRICT 12',
    heroTitle: 'Contact Us & Book Consultation',
    heroSubtitle: 'Reach out to receive a personalized learning roadmap and book a 100% free 4-skill proficiency assessment with iCANCAM experts.',
    hotlineBadge: 'Hotline: 0909 123 456',
    hoursBadge: 'Mon - Sun: 08:00 - 21:30',
    campusTitle: 'iCANCAM Headquarters',
    subTag: 'Hoc Mon & District 12',
    addressLabel: 'Official Address:',
    hotlineLabel: 'Admissions & Support Hotline:',
    emailLabel: 'Support Email:',
    mapsBtn: 'Directions on Google Maps',
    hoursTitle: 'Center Operating Hours',
    hoursDesc: 'Monday – Sunday | 08:00 – 21:30 (Open 7 days a week)',
    commitTitle: 'Consultation Commitment',
    commitDesc: 'Advisors reply within 24h & Free 4-skill placement test 100%.',
    formTitle: 'Book Consultation & Placement Test',
    formDesc: 'Students receive a free 4-skill assessment and personalized roadmap.',
    successAlert: 'Request submitted! iCANCAM advisors will contact you within 24 hours.',
    fullNameLabel: 'Full Name *',
    phoneLabel: 'Phone Number *',
    emailInputLabel: 'Email Address',
    branchLabel: 'Preferred Campus *',
    branchOpt1: 'Trung My Tay Campus (344 A To 13 KP 1, HCMC)',
    branchOpt2: 'Hoc Mon & District 12 Campus',
    courseLabel: 'Interested Course *',
    messageLabel: 'Message / Additional Requests',
    submitBtn: 'Submit Consultation Request',
    mapTitle: 'iCANCAM Map Location',
    openAppBtn: 'Open Google Maps App',
  },
  careers: {
    heroBadge: 'JOIN THE iCANCAM TEAM',
    heroTitlePrefix: 'Career Opportunities & ',
    heroTitleHighlight: 'Professional Growth',
    heroSubtitle: 'Create 21st-century modern learning environments at Hoc Mon & District 12 with iCANCAM, empowering young learners to master English and achieve lifelong self-learning.',
    filterAll: 'All Positions',
    filterAcademic: 'Academic & Faculty',
    filterSales: 'Consultation & Admissions',
    filterOps: 'Operations & Services',
    cultureTag: 'WORKPLACE CULTURE',
    cultureTitle: 'Why Join iCANCAM\'s Educational Mission?',
    cultureCard1Title: 'Competitive Compensation',
    cultureCard1Desc: 'Rewarding salary based on merit, KPI bonuses & teaching quality rewards every month/quarter.',
    cultureCard2Title: 'Continuous Masterclass Training',
    cultureCard2Desc: 'Regular masterclass training on 4Ls + LETI methodology & Smartboard technology with expert trainers.',
    cultureCard3Title: 'Clear Advancement Pathway',
    cultureCard3Desc: 'Transparent evaluation pathways to Department Head, Academic Manager & Center Director.',
    cultureCard4Title: 'Vibrant & Cohesive Culture',
    cultureCard4Desc: 'Energetic colleagues, respectful & supportive culture with annual Teambuilding events.',
    deptLabel: 'Department:',
    typeLabel: 'Type:',
    locLabel: 'Location:',
    viewDetailBtn: 'View Details',
    applyNowBtn: 'Apply Now',
    ctaTitle: 'Didn\'t Find a Matching Position?',
    ctaDesc: 'Send your CV to iCANCAM\'s Talent Pool. We are always looking for exceptional talents to join our team long-term!',
    ctaSendEmailBtn: 'Send CV via Email',
    modalReqTitle: 'Job Requirements',
    modalBenTitle: 'Benefits & Perks',
    modalFormTitle: 'Quick Application Form',
    fullNameLabel: 'Full Name *',
    fullNamePlaceholder: 'Enter full name...',
    phoneLabel: 'Phone Number *',
    phonePlaceholder: 'Enter phone number...',
    emailLabel: 'Email Address *',
    noteLabel: 'CV Link / Additional Notes',
    notePlaceholder: 'Paste Google Drive CV link or experience notes...',
    submitApplyBtn: 'Submit Application',
    successAlert: '🎉 Application submitted! iCANCAM HR will contact you within 48 business hours.',
  },
  faq: {
    heroBadge: 'iCANCAM CONSULTATION & FAQ',
    heroTitlePrefix: 'Frequently Asked ',
    heroTitleHighlight: 'Questions',
    heroSubtitle: 'Comprehensive answers regarding 4Ls + LETI methods, outcome guarantees, tuition fees, and campus info in Hoc Mon & District 12.',
    searchPlaceholder: 'Search keywords (e.g. IELTS, guarantee, tuition...)',
    filterAll: 'All Questions',
    filterMethod: 'Method & Classrooms',
    filterCurriculum: 'Pathway & Guarantees',
    filterTuition: 'Tuition & Discounts',
    filterLocation: 'Campuses & Schedule',
    noResultsTitle: 'No matching questions found',
    noResultsDesc: 'Try searching with different keywords or contact iCANCAM advisors directly.',
    guaranteeTag: 'OUR COMMITMENTS',
    guaranteeTitle: 'iCANCAM Guarantees That',
    pillar1Title: '24/7 Direct Support',
    pillar1Desc: 'Academic advisors ready to assist with learning roadmaps via Hotline & Zalo.',
    pillar2Title: 'Written Legal Guarantee',
    pillar2Desc: '100% enrolled students receive a legal written output contract.',
    pillar3Title: 'Sustainable Self-Learning',
    pillar3Desc: 'Cultivate independent research skills empowering lifelong English mastery.',
    ctaTitle: 'Need More Information from iCANCAM?',
    ctaDesc: 'Reach out to iCANCAM anytime. Our advisors at Hoc Mon & District 12 will assist you promptly.',
    ctaPrimaryBtn: 'Book Free Consultation',
    ctaSecondaryBtn: 'Hotline: 0909 123 456',
  },
  news: {
    heroBadge: 'iCANCAM NEWS & EVENTS',
    heroTitlePrefix: 'Latest News & ',
    heroTitleHighlight: 'Featured Events',
    heroSubtitle: 'Stay updated with educational activities, academic competitions, scholarship info, and digital parenting guides from iCANCAM.',
    filterAll: 'All News',
    filterEvents: 'Events & Competitions',
    filterScholarship: 'Scholarship Programs',
    filterTips: 'Parenting Guides',
    latestTag: 'LATEST',
    readMoreBtn: 'Read Full Article',
    gridTag: 'ARTICLE LISTING',
    gridTitle: 'Educational News & Recent Activities',
    readCardBtn: 'Read article',
    newsletterTitle: 'Subscribe to Educational Newsletter & Scholarship Info',
    newsletterDesc: 'Subscribe to your email to never miss academic contests, scholarship opportunities, and English learning tips from iCANCAM.',
    newsletterSuccess: 'Subscribed successfully! Thank you for subscribing to iCANCAM newsletter.',
    newsletterInputPlaceholder: 'Enter your email address...',
    newsletterSubmitBtn: 'Subscribe',
    modalCourseConsultBtn: 'Book Course Consultation',
  },
};

