export const vi = {
  nav: {
    about: 'GIỚI THIỆU',
    curriculum: 'CHƯƠNG TRÌNH HỌC',
    news: 'TIN TỨC - SỰ KIỆN',
    faq: 'HỎI ĐÁP',
    careers: 'TUYỂN DỤNG',
    contact: 'LIÊN HỆ',
    welcome: 'Chào',
    logout: 'Đăng xuất',
  },
  footer: {
    copyright: 'THIEUNAM iCAM ©',
    allRightsReserved: 'Bản quyền thuộc về ICANCAM.',
  },
  shortcuts: {
    zalo: 'Chat Zalo',
    messenger: 'Chat Messenger',
    email: 'Gửi Email',
  },
  home: {
    registerNow: 'ĐĂNG KÝ NGAY',
    newsOverviewLabel: 'TỔNG QUAN TIN TỨC & SỰ KIỆN',
    achievementsLabel: 'THÀNH TỰU NỔI BẬT CỦA ICAM',
    yearsExp: '10 năm',
    yearsExpDesc: 'kinh nghiệm đào tạo tiếng Anh',
    cambridgeShields: '15/15 khiên',
    cambridgeShieldsDesc: 'chứng chỉ Cambridge Starters, Movers & Flyers',
    studentsCount: '10.000+',
    studentsCountDesc: 'học viên tin tưởng theo học tại Hóc Môn & Quận 12',
    teachersCount: '100%',
    teachersCountDesc: 'giáo viên bản xứ & Việt Nam đạt chứng chỉ TESOL / CELTA',
    iSMARTLabel: 'HỆ THỐNG DẠY HỌC TRỰC TUYẾN 21ST',
    iSMARTTitle: 'iCAM ONLINE — HỌC KHÔNG GIỚI HẠN VỚI CÔNG NGHỆ HOLOGRAM & SMARTBOARD',
    iSMARTDesc: 'Mô hình học tiếng Anh trực tuyến hiện đại kết hợp bảng tương tác thông minh Smartboard, giáo trình chuẩn Anh Quốc và công nghệ Hologram đa chiều giúp học sinh tiếp thu kiến thức trực quan sinh động.',
    teachersLabel: 'ĐỘI NGŨ GIÁO VIÊN BẢN XỨ & VIỆT NAM CHUYÊN MÔN CAO',
    studentsLabel: 'HỌC VIÊN XUẤT SẮC ĐANG THEO HỌC TẠI ICAM',
    parentsLabel: 'CẢM NHẬN TỪ PHỤ HUYNH HỌC VIÊN ICAM',
    regTitle: 'Đăng Ký Tư Vấn & Đánh Giá Năng Lực 4 Kỹ Năng Miễn Phí',
    regDesc: 'Điền thông tin bên dưới để chuyên viên giáo dục ICANCAM liên hệ tư vấn lộ trình học phù hợp nhất cho con bạn.',
    regNameLabel: 'Họ và tên Phụ huynh / Học viên *',
    regNamePlaceholder: 'Nhập họ và tên...',
    regPhoneLabel: 'Số điện thoại liên hệ *',
    regPhonePlaceholder: 'Nhập số điện thoại...',
    regEmailLabel: 'Địa chỉ Email',
    regEmailPlaceholder: 'email@example.com...',
    regAgeLabel: 'Độ tuổi học sinh *',
    regAgePlaceholder: 'Ví dụ: 6 tuổi, 12 tuổi...',
    regCampusLabel: 'Khu vực cơ sở *',
    regCampusHocMon: 'Cơ sở Hóc Môn & Quận 12 (344 A Tổ 13 KP 1, Trung Mỹ Tây)',
    regSubmitBtn: 'Đăng Ký Nhận Tư Vấn Miễn Phí',
  },
  about: {
    heroBadge: 'ICANCAM — HÓC MÔN & QUẬN 12',
    heroTitle: 'Mô Hình Giáo Dục Tiếng Anh Thế Kỷ 21',
    heroTagline: 'Tự tin giao tiếp • Học tập độc lập • Làm chủ ngôn ngữ',
    heroDesc: 'ICANCAM tiên phong áp dụng mô hình giáo dục hiện đại, kết hợp phương pháp 4Ls và LETI giúp học sinh không chỉ học tiếng Anh mà còn chủ động làm chủ và tự học suốt đời.',
    exploreBtn: 'Khám Phá Phương Pháp',
    consultBtn: 'Đăng Ký Tư Vấn',
    campusHocMon: 'Cơ sở Hóc Môn',
    campusQ12: 'Cơ sở Quận 12',
    missionTag: 'SỨ MỆNH CỦA ICANCAM',
    missionTitle: 'Khai Mở Năng Lực Tự Học Độc Lập',
    missionSubtitle: 'Sứ mệnh của ICANCAM không chỉ dừng lại ở việc truyền đạt kiến thức, mà là đồng hành biến học sinh thành người sử dụng tiếng Anh tự tin, độc lập và có khả năng tự phát triển tri thức suốt đời.',
    dec1Title: 'Tuyên Ngôn 1',
    dec1Decl: 'I can communicate in English.',
    dec1Sub: 'Tôi có thể giao tiếp Tiếng Anh tự tin.',
    dec1Desc: 'Phá vỡ rào cản e ngại, giúp học viên phản xạ tự nhiên trong môi trường 100% Tiếng Anh.',
    dec2Title: 'Tuyên Ngôn 2',
    dec2Decl: 'I can master English.',
    dec2Sub: 'Tôi có thể làm chủ Tiếng Anh.',
    dec2Desc: 'Làm chủ đầy đủ 4 kỹ năng Nghe - Nói - Đọc - Viết và ứng dụng vào học thuật & đời sống.',
    dec3Title: 'Tuyên Ngôn 3',
    dec3Decl: 'I can learn English independently.',
    dec3Sub: 'Tôi có thể tự học Tiếng Anh độc lập.',
    dec3Desc: 'Trang bị phương pháp tự nghiên cứu, tư duy phản biện để chủ động học tập suốt đời.',
    valuesTag: 'GIÁ TRỊ CỐT LÕI',
    valuesTitle: '4 Trụ Cột Năng Lực Tại ICANCAM',
    val1Title: 'Tự Tin Giao Tiếp',
    val1Desc: 'Tự tin biểu đạt ý tưởng và tranh luận bằng tiếng Anh tự nhiên.',
    val2Title: 'Tự Học Độc Lập',
    val2Desc: 'Hình thành thói quen và phương pháp tự nghiên cứu lâu dài.',
    val3Title: 'Làm Chủ Ngôn Ngữ',
    val3Desc: 'Phát triển toàn diện 4 kỹ năng chuẩn học thuật & ứng dụng.',
    val4Title: 'Phát Triển Bền Vững',
    val4Desc: 'Xây dựng tư duy phản biện và phong thái công dân toàn cầu.',
    compTag: 'SỰ KHÁC BIỆT VƯỢT TRỘI',
    compTitle: 'So Sánh Mô Hình Giáo Dục Tiếng Anh',
    toggleTrad: 'Lối Học Truyền Thống',
    toggleCAM: 'ICANCAM (Thế Kỷ 21)',
    tradHeader: 'Lối Học Truyền Thống Thụ Động',
    trad1: 'Ghi nhớ ngữ pháp thụ động, ít có cơ hội thực hành nghe nói',
    trad2: 'Tập trung học để đối phó thi cử, nhanh quên sau khóa học',
    trad3: 'Học sinh thiếu tự tin, e ngại khi gặp người bản xứ',
    trad4: 'Phụ thuộc hoàn toàn vào thầy cô, thiếu kỹ năng tự học',
    camHeader: 'Mô Hình ICANCAM Tương Tác 21st',
    cam1: 'Thực hành tương tác 80% thời lượng với phương pháp 4Ls + LETI',
    cam2: 'Lớp học Smartboard trực quan sinh động với giáo trình Anh Quốc',
    cam3: 'Tự tin phản xạ tự nhiên và thuyết trình trước đám đông',
    cam4: 'Làm chủ phương pháp tự học độc lập suốt đời',
    methodTag: 'PHƯƠNG PHÁP GIẢNG DẠY',
    methodTitle: 'Mô Hình Kết Hợp 4Ls & LETI',
    methodDesc: 'Phương pháp giáo dục độc quyền giúp tối ưu hóa khả năng tiếp thu và phản xạ ngôn ngữ của học sinh.',
    tab4Ls: 'Mô Hình 4Ls (4 Kỹ Năng Cốt Lõi)',
    tabLETI: 'Phương Pháp LETI (Tương Tác 2 Chiều)',
    lsListening: 'Listening (Nghe)',
    lsListeningDesc: 'Nghe thẩm thấu qua âm thanh chuẩn bản xứ và phần mềm Anh Quốc.',
    lsSpeaking: 'Speaking (Nói)',
    lsSpeakingDesc: 'Luyện phản xạ nói tự nhiên, chuẩn hóa phát âm IPA ngay từ đầu.',
    lsReading: 'Reading (Đọc)',
    lsReadingDesc: 'Đọc hiểu phân tích văn bản, mở rộng từ vựng học thuật phong phú.',
    lsWriting: 'Writing (Viết)',
    lsWritingDesc: 'Rèn luyện kỹ năng viết luận, tư duy logic và diễn đạt mạch lạc.',
    classTag: 'CƠ SỞ VẬT CHẤT 21ST',
    classTitle: 'Lớp Học Thông Minh Thế Kỷ 21',
    classDesc: 'Trang thiết bị công nghệ hiện đại hỗ trợ tối đa cho việc học tương tác trực quan.',
    class1Title: 'Bảng Tương Tác Smartboard',
    class1Desc: '100% phòng học trang bị màn hình cảm ứng tương tác trực tiếp.',
    class2Title: 'Phần Mềm Chuẩn Anh Quốc',
    class2Desc: 'Giáo trình & phần mềm kiểm định bởi các tổ chức xuất bản hàng đầu.',
    class3Title: 'Học Đa Phương Tiện Multimedia',
    class3Desc: 'Hình ảnh 3D, video sinh động giúp bài học dễ nhớ.',
    class4Title: 'Môi Trường 100% Tiếng Anh',
    class4Desc: 'Không gian nhúng ngôn ngữ giúp kích hoạt phản xạ tự nhiên.',
    journeyTag: 'LỘ TRÌNH PHÁT TRIỂN',
    journeyTitle: 'Hành Trình Khai Mở Năng Lực Học Viên',
    jStep1Title: '1. Khai Mở',
    jStep1Desc: 'Khơi dậy đam mê và xây dựng nền tảng ngữ âm Phonics chuẩn.',
    jStep2Title: '2. Tương Tác',
    jStep2Desc: 'Thực hành phản xạ giao tiếp hai chiều qua mô hình LETI.',
    jStep3Title: '3. Làm Chủ',
    jStep3Desc: 'Làm chủ 4Ls và tự tin chinh phục các chứng chỉ quốc tế.',
    jStep4Title: '4. Tự Học Độc Lập',
    jStep4Desc: 'Làm chủ phương pháp nghiên cứu tự học suốt đời.',
    outcomesTag: 'GIÁ TRỊ NHẬN ĐƯỢC',
    outcomesTitle: 'Kết Quả Đạt ĐƯỢC Sau Khóa Học',
    out1: 'Tự tin phản xạ tiếng Anh tự nhiên với người bản xứ',
    out2: 'Thành thạo 4 kỹ năng Nghe - Nói - Đọc - Viết chuẩn học thuật',
    out3: 'Làm chủ phương pháp tự học độc lập và tư duy phản biện',
    out4: 'Đạt điểm cao trong các kỳ thi Cambridge & IELTS',
    out5: 'Kỹ năng thuyết trình và làm việc nhóm hiệu quả',
    out6: 'Sẵn sàng hội nhập và trở thành Công dân toàn cầu',
    storyBadge: 'CAM KẾT CHẤT LƯỢNG VỚI HÓC MÔN & QUẬN 12',
    storyTitle: 'Hành Trình Mang Giáo Dục Thế Kỷ 21 Đến Hóc Môn & Quận 12',
    storyP1: 'ICANCAM được thành lập với mục tiêu mang mô hình giáo dục Tiếng Anh chuẩn quốc tế thế kỷ 21 về với phụ huynh và học sinh tại khu vực Hóc Môn và Quận 12, TP. Hồ Chí Minh.',
    storyP2: 'Chúng tôi tin rằng mọi học sinh đều có tiềm năng ngôn ngữ vô hạn nếu được học tập trong môi trường tương tác hiện đại, tiếp cận đúng phương pháp 4Ls + LETI và được khơi gợi niềm đam mê tự học độc lập.',
    ctaTitle: 'Sẵn Sàng Cùng ICANCAM Làm Chủ Tiếng Anh?',
    ctaDesc: 'Đăng ký ngay hôm nay để nhận tư vấn lộ trình học cá nhân hóa và xếp lịch kiểm tra trình độ 4 kỹ năng miễn phí.',
    ctaPrimaryBtn: 'Đăng Ký Tư Vấn Ngay',
    ctaSecondaryBtn: 'Xem Chương Trình Học',
  },
  curriculum: {
    heroBadge: 'LỘ TRÌNH ĐÀO TẠO CHUẨN QUỐC TẾ',
    heroTitle: 'Chương Trình Đào Tạo ICANCAM',
    heroSubtitle: 'Lộ trình học tối ưu kết hợp mô hình 4Ls + LETI và công nghệ 21st, giúp học viên phát triển toàn diện 4 kỹ năng và khả năng tự học độc lập suốt đời.',
    filterAll: 'Tất Cả Chương Trình',
    filterKids: 'Trẻ Em & Mầm Non (4-11t)',
    filterTeens: 'Thiếu Niên (12-15t)',
    filterIelts: 'Luyện Thi IELTS',
    filterComm: 'Giao Tiếp Thực Chiến',
    filterOnline: 'iCAM Online',
    durationLabel: 'Thời lượng:',
    targetGroupLabel: 'Đối tượng:',
    commitmentLabel: 'Cam kết đầu ra:',
    viewSyllabusBtn: 'Xem Chi Tiết Lộ Trình',
    registerBtn: 'Đăng Ký Tư Vấn',
    whyTag: 'ƯU ĐIỂM VƯỢT TRỘI',
    whyTitle: 'Tại Sao Lộ Trình Đào Tạo Tại ICANCAM Hiệu Quả?',
    ctaTitle: 'Chưa Biết Khóa Học Nào Phù Hợp Với Con?',
    ctaDesc: 'Đăng ký kiểm tra trình độ Tiếng Anh miễn phí và nhận lộ trình học cá nhân hóa từ các chuyên gia ICANCAM ngay hôm nay.',
    ctaPrimaryBtn: 'Đăng Ký Test Trình Độ Miễn Phí',
    ctaSecondaryBtn: 'Hotline Tư Vấn Trực Tiếp',
  },
  contact: {
    heroBadge: 'ICANCAM — HÓC MÔN & QUẬN 12',
    heroTitle: 'Liên Hệ & Đăng Ký Tư Vấn',
    heroSubtitle: 'Đừng ngần ngại liên hệ để nhận tư vấn lộ trình học cá nhân hóa và đăng ký kiểm tra trình độ 4 kỹ năng hoàn toàn miễn phí cùng đội ngũ chuyên gia ICANCAM.',
    hotlineBadge: 'Hotline: 0909 123 456',
    hoursBadge: 'T2 - CN: 08:00 - 21:30',
    campusTitle: 'Trụ Sở ICANCAM',
    subTag: 'Hóc Môn & Quận 12',
    addressLabel: 'Địa chỉ chính thức:',
    hotlineLabel: 'Hotline tuyển sinh & tư vấn:',
    emailLabel: 'Email hỗ trợ:',
    mapsBtn: 'Định Vị Trên Google Maps',
    hoursTitle: 'Giờ Làm Việc Trung Tâm',
    hoursDesc: 'Thứ 2 – Chủ Nhật | 08:00 – 21:30 (Mở cửa tất cả các ngày trong tuần)',
    commitTitle: 'Cam Kết Tư Vấn',
    commitDesc: 'Tư vấn viên liên hệ hỗ trợ trong vòng 24h & Test trình độ miễn phí 100%.',
    formTitle: 'Đăng Ký Tư Vấn & Test Trình Độ',
    formDesc: 'Học viên được kiểm tra trình độ 4 kỹ năng miễn phí và nhận lộ trình học cá nhân hóa.',
    successAlert: 'Gửi thông tin thành công! Bộ phận tư vấn ICANCAM sẽ liên hệ lại với bạn trong vòng 24h làm việc.',
    fullNameLabel: 'Họ và tên *',
    phoneLabel: 'Số điện thoại *',
    emailInputLabel: 'Địa chỉ Email',
    branchLabel: 'Cơ sở đăng ký *',
    branchOpt1: 'Cơ sở Trung Mỹ Tây (344 A Tổ 13 KP 1, HCM)',
    branchOpt2: 'Cơ sở Hóc Môn & Quận 12',
    courseLabel: 'Khóa học quan tâm *',
    messageLabel: 'Lời nhắn / Yêu cầu thêm',
    submitBtn: 'Gửi Yêu Cầu Tư Vấn Ngay',
    mapTitle: 'Vị Trí Bản Đồ Trung Tâm ICANCAM',
    openAppBtn: 'Mở Ứng Dụng Google Maps Chỉ Đường',
  },
};

