export const vi = {
  nav: {
    about: 'GIỚI THIỆU',
    curriculum: 'CHƯƠNG TRÌNH HỌC',
    news: 'TIN TỨC - SỰ KIỆN',
    faq: 'HỎI ĐÁP',
    careers: 'TUYỂN DỤNG',
    contact: 'LIÊN HỆ',
    welcome: 'Chào',
    logout: 'Đăng xuất',
  },
  footer: {
    copyright: 'THIEUNAM iCANCAM ©',
    allRightsReserved: 'Bản quyền thuộc về iCANCAM.',
  },
  shortcuts: {
    scrollTop: 'Lên đầu trang',
    zalo: 'Chat Zalo',
    messenger: 'Chat Messenger',
    email: 'Gửi Email',
  },
  home: {
    registerNow: 'ĐĂNG KÝ NGAY',
    newsOverviewLabel: 'TỔNG QUAN TIN TỨC & SỰ KIỆN',
    achievementsLabel: 'THÀNH TỰU NỔI BẬT CỦA iCANCAM',
    yearsExp: '10 năm',
    yearsExpDesc: 'kinh nghiệm đào tạo tiếng Anh',
    cambridgeShields: '15/15 khiên',
    cambridgeShieldsDesc: 'chứng chỉ Cambridge Starters, Movers & Flyers',
    studentsCount: '10.000+',
    studentsCountDesc: 'học viên tin tưởng theo học tại Hóc Môn & Quận 12',
    teachersCount: '100%',
    teachersCountDesc: 'giáo viên bản xứ & Việt Nam đạt chứng chỉ TESOL / CELTA',
    iSMARTLabel: 'HỆ THỐNG DẠY HỌC TRỰC TUYẾN 21ST',
    iSMARTTitle: 'iCANCAM ONLINE — HỌC KHÔNG GIỚI HẠN VỚI CÔNG NGHỆ HOLOGRAM & SMARTBOARD',
    iSMARTDesc: 'Mô hình học tiếng Anh trực tuyến hiện đại kết hợp bảng tương tác thông minh Smartboard, giáo trình chuẩn Anh Quốc và công nghệ Hologram đa chiều giúp học sinh tiếp thu kiến thức trực quan sinh động.',
    teachersLabel: 'ĐỘI NGŨ GIÁO VIÊN BẢN XỨ & VIỆT NAM CHUYÊN MÔN CAO',
    studentsLabel: 'HỌC VIÊN XUẤT SẮC ĐANG THEO HỌC TẠI iCANCAM',
    parentsLabel: 'CẢM NHẬN TỪ PHỤ HUYNH HỌC VIÊN iCANCAM',
    regTitle: 'Đăng Ký Tư Vấn & Đánh Giá Năng Lực 4 Kỹ Năng Miễn Phí',
    regDesc: 'Điền thông tin bên dưới để chuyên viên giáo dục iCANCAM liên hệ tư vấn lộ trình học phù hợp nhất cho con bạn.',
    regNameLabel: 'Họ và tên Phụ huynh / Học viên *',
    regNamePlaceholder: 'Nhập họ và tên...',
    regPhoneLabel: 'Số điện thoại liên hệ *',
    regPhonePlaceholder: 'Nhập số điện thoại...',
    regEmailLabel: 'Địa chỉ Email',
    regEmailPlaceholder: 'email@example.com...',
    regAgeLabel: 'Độ tuổi học sinh *',
    regAgePlaceholder: 'Ví dụ: 6 tuổi, 12 tuổi...',
    regCampusLabel: 'Khu vực cơ sở *',
    regCampusHocMon: 'Cơ sở Hóc Môn & Quận 12 (344 A Tổ 13 KP 1, Trung Mỹ Tây)',
    regSubmitBtn: 'Đăng Ký Nhận Tư Vấn Miễn Phí',
  },
  about: {
    heroBadge: 'iCANCAM — HÓC MÔN & QUẬN 12',
    heroTitlePrefix: 'Mô\u00A0Hình\u00A0Giáo\u00A0Dục Tiếng\u00A0Anh ',
    heroTitleHighlight: 'Thế\u00A0Kỷ\u00A021',
    heroTagline: 'Tự\u00A0tin giao\u00A0tiếp • Học\u00A0tập độc\u00A0lập • Làm\u00A0chủ ngôn\u00A0ngữ',
    heroDescription: 'iCANCAM tiên phong áp dụng mô hình giáo dục hiện đại, kết hợp phương pháp 4Ls và LETI giúp học sinh không chỉ học tiếng\u00A0Anh mà còn chủ động làm chủ và tự\u00A0học suốt đời.',
    exploreMethodBtn: 'Khám Phá Phương Pháp',
    registerBtn: 'Đăng Ký Tư Vấn',
    missionTag: 'SỨ MỆNH CỦA iCANCAM',
    missionTitlePrefix: 'Khai\u00A0Mở Năng\u00A0Lực ',
    missionTitleHighlight: 'Tự\u00A0Học Độc\u00A0Lập',
    missionSubtitle: 'Sứ mệnh của iCANCAM không chỉ dừng lại ở việc truyền đạt kiến\u00A0thức, mà là đồng\u00A0hành biến học sinh thành người sử dụng tiếng\u00A0Anh tự tin, độc\u00A0lập và có khả năng tự phát\u00A0triển tri thức suốt đời.',
    declaration1Sub: 'Tôi có thể giao tiếp Tiếng Anh tự tin',
    declaration1Desc: 'Tự tin biểu đạt ý tưởng, giao tiếp tự nhiên và không rào cản trong mọi tình huống giao tiếp đời sống.',
    declaration2Sub: 'Tôi có thể làm chủ Tiếng Anh',
    declaration2Desc: 'Làm chủ cả 4 kỹ năng Nghe - Nói - Đọc - Viết và chủ động ứng dụng ngôn ngữ linh hoạt theo mục tiêu cá nhân.',
    declaration3Sub: 'Tôi có thể tự học Tiếng Anh độc lập',
    declaration3Desc: 'Sở hữu phương pháp tự học hiệu quả, có khả năng tự tìm tòi, mở rộng tri thức ngôn ngữ mà không phụ thuộc.',
    valuesTag: 'GIÁ TRỊ CỐT LÕI',
    valuesTitle: '4 Trụ Cột Năng Lực Học Viên',
    val1Title: 'Tự\u00A0Tin Giao\u00A0Tiếp',
    val1Desc: 'Loại bỏ sự e ngại, giúp học sinh chủ động đặt câu hỏi, thảo luận và bày tỏ quan điểm bằng tiếng Anh.',
    val2Title: 'Tự\u00A0Học Độc\u00A0Lập',
    val2Desc: 'Trang bị tư duy tự nghiên cứu, giúp học sinh chủ động tiếp cận nguồn tri thức mới mà không bị động.',
    val3Title: 'Làm\u00A0Chủ Ngôn\u00A0Ngữ',
    val3Desc: 'Hiểu sâu bản chất ngôn ngữ để sử dụng tự nhiên như công cụ tư duy thay vì học thuộc lòng công thức.',
    val4Title: 'Phát\u00A0Triển Bền\u00A0Vững',
    val4Desc: 'Tạo nền tảng vững chắc để học sinh tiếp tục tự học và nâng cao trình độ trong suốt hành trình tương lai.',
    whyTag: 'SỰ KHÁC BIỆT',
    whyTitle: 'Học Qua Tương\u00A0Tác Thay Vì Ghi\u00A0Nhớ Thụ\u00A0Động',
    whySubtitle: 'iCANCAM thay thế lối học vẹt rập khuôn bằng môi trường chủ động tương\u00A0tác và ứng\u00A0dụng thực\u00A0tế.',
    tabTraditional: 'Học Truyền Thống',
    tabCam: 'Mô Hình iCANCAM ★',
    tradHeaderTitle: 'Học Tiếng Anh Truyền Thống',
    tradHeaderBadge: 'Ghi nhớ thụ động',
    tradItem1: 'Học thuộc lòng từ vựng và công thức ngữ pháp khô khan.',
    tradItem2: 'Nghe giảng một chiều, ít cơ hội thực hành giao tiếp.',
    tradItem3: 'Học để đối phó bài kiểm tra, thiếu tính ứng dụng đời sống.',
    tradItem4: 'Bị động phụ thuộc vào giáo viên, thiếu phương pháp tự học.',
    camHeaderTitle: 'Phương Pháp iCANCAM',
    camHeaderBadge: '4Ls + LETI Tương tác',
    camItem1: 'Học qua tương tác, thảo luận nhóm và trải nghiệm tình huống thực tế.',
    camItem2: 'Môi trường 100% tiếng Anh giúp kích hoạt phản xạ tự nhiên.',
    camItem3: 'Rèn luyện tư duy phản biện, kỹ năng làm việc nhóm và giải quyết vấn đề.',
    camItem4: 'Hình thành năng lực tự học độc lập và tự duy trì tri thức lâu dài.',
    methodTag: 'PHƯƠNG PHÁP GIẢNG DẠY',
    methodTitlePrefix: 'Sự Kết Hợp Đột Phá ',
    methodTitleHighlight: '4Ls & LETI',
    methodSubtitle: 'Mô hình giáo dục tiếng\u00A0Anh thế\u00A0kỷ\u00A021 kết hợp hoàn thiện 4 kỹ năng ngôn ngữ cốt lõi với phương pháp học qua tương tác.',
    tab4Ls: 'Mô Hình 4Ls (Kỹ Năng Cốt Lõi)',
    tabLeti: 'Phương Pháp LETI (Tương Tác)',
    ls1Title: 'Listening (Nghe)',
    ls1Desc: 'Luyện nghe đa dạng ngữ điệu, tiếp thu thông tin chủ động và phản xạ nhanh.',
    ls2Title: 'Speaking (Nói)',
    ls2Desc: 'Phát âm chuẩn xác, diễn đạt ý tưởng trôi chảy và tự tin trước đám đông.',
    ls3Title: 'Reading (Đọc)',
    ls3Desc: 'Đọc hiểu chuyên sâu, phân tích ngữ cảnh và tích lũy vốn từ phong phú.',
    ls4Title: 'Writing (Viết)',
    ls4Desc: 'Tư duy logic, cấu trúc câu mạch lạc và biểu đạt văn bản hiệu quả.',
    letiBannerTitle: 'LETI — Learning English Through Interactions',
    letiBannerSub: 'Học Tiếng Anh Thông Qua Tương Tác Trực Tiếp & Trải Nghiệm Đa Dạng',
    letiItem1Title: 'Interaction (Tương Tác)',
    letiItem1Desc: 'Tương tác hai chiều liên tục giữa giáo viên và học viên trong lớp.',
    letiItem2Title: 'Communication (Giao Tiếp)',
    letiItem2Desc: 'Thực hành trao đổi, trình bày quan điểm bằng tiếng Anh tự nhiên.',
    letiItem3Title: 'Application (Ứng Dụng)',
    letiItem3Desc: 'Đưa kiến thức học được vào giải quyết các bài toán thực tế.',
    letiItem4Title: 'Discussion (Thảo Luận)',
    letiItem4Desc: 'Thảo luận nhóm phát triển tư duy phản biện và làm việc đồng đội.',
    letiItem5Title: 'Practice (Thực Hành)',
    letiItem5Desc: 'Luyện tập liên tục qua các bài tập tình huống và dự án học tập.',
    letiItem6Title: 'Real-Life Activities (Hoạt Động Thực Tế)',
    letiItem6Desc: 'Trải nghiệm ngôn ngữ trong môi trường giao tiếp thực sự.',
    classroomTag: 'MÔI TRƯỜNG HỌC TẬP',
    classroomTitle: 'Lớp Học Thông Minh Thế Kỷ 21',
    classroomSubtitle: 'Không gian học tập tích hợp công nghệ hiện đại mang lại trải nghiệm tương tác trực quan sống động.',
    class1Title: 'Bảng Tương Tác Thông Minh',
    class1Desc: 'Smart Interactive Boards giúp bài học trở nên sinh động, cho phép học sinh trực tiếp thao tác và tương tác với nội dung giảng dạy.',
    class2Title: 'Phần Mềm Giáo Dục Anh Quốc',
    class2Desc: 'British Educational Software chuẩn quốc tế cung cấp nguồn tài nguyên học tập đa dạng, phong phú và tương tác cao.',
    class3Title: 'Học Tập Đa Phương Tiện',
    class3Desc: 'Multimedia & Technology-Enhanced Education kết hợp hình ảnh, âm thanh và công nghệ giúp kích hoạt tối đa khả năng ghi nhớ.',
    class4Title: 'Môi Trường 100% Tiếng Anh',
    class4Desc: '100% English-Speaking Environment tạo không gian "tắm ngôn ngữ" hoàn toàn, kích thích phản xạ giao tiếp tự nhiên.',
    journeyTag: 'HÀNH TRÌNH HỌC VIÊN',
    journeyTitle: '4 Bước Phát Triển Năng Lực Ngôn Ngữ',
    step1Title: 'Khai Mở & Tiếp Cận',
    step1Desc: 'Tiếp xúc với môi trường 100% tiếng Anh và tiếp cận phương pháp học qua tương tác LETI.',
    step2Title: 'Tương Tác & Giao Tiếp',
    step2Desc: 'Thực hành liên tục 4Ls qua thảo luận nhóm, hoạt động thực tế và phản hồi hai chiều.',
    step3Title: 'Tự Tin & Làm Chủ',
    step3Desc: 'Hình thành phản xạ tự nhiên, tự tin trình bày ý tưởng và làm chủ cả 4 kỹ năng tiếng Anh.',
    step4Title: 'Tự Học Độc Lập',
    step4Desc: 'Làm chủ phương pháp tự học, tự duy trì và tiếp tục mở rộng tri thức suốt đời.',
    outcomesTag: 'GIÁ TRỊ NHẬN ĐƯỢC',
    outcomesTitle: '6 Năng Lực Toàn Diện Sau Khóa Học',
    out1Title: 'Tự Tin (Confidence)',
    out1Desc: 'Mạnh dạn thể hiện bản thân và giao tiếp tự nhiên.',
    out2Title: 'Kỹ Năng Giao Tiếp (Communication)',
    out2Desc: 'Biểu đạt suy nghĩ rõ ràng và lắng nghe thấu hiểu.',
    out3Title: 'Khả Năng Tự Học Độc Lập (Independent Learning)',
    out3Desc: 'Chủ động tìm tòi và phát triển tri thức không phụ thuộc.',
    out4Title: 'Tư Duy Phản Biện (Critical Thinking)',
    out4Desc: 'Phân tích thông tin và giải quyết vấn đề logic.',
    out5Title: 'Tiếng Anh Thực Tiễn (Practical English)',
    out5Desc: 'Ứng dụng hiệu quả vào đời sống và học tập.',
    out6Title: 'Tư Duy Toàn Cầu (Global Mindset)',
    out6Desc: 'Sẵn sàng hội nhập và kết nối với thế giới.',
    storyTag: 'HÀNH TRÌNH ĐỔI MỚI',
    storyTitle: 'Tiên Phong Giáo Dục Tại Hóc Môn & Quận 12',
    storyP1: 'Với kinh nghiệm tích lũy trong giảng dạy tiếng Anh, iCANCAM không ngừng nghiên cứu và đổi mới nhằm mang mô hình giáo dục tiên phong thế kỷ 21 tới học sinh tại Hóc Môn và Quận 12.',
    storyP2: 'Chúng tôi tin rằng mỗi học sinh đều có tiềm năng lớn để trở thành một người sử dụng tiếng Anh thành thạo và tự lập. Bằng sự kết hợp giữa 4Ls + LETI và công nghệ lớp học thông minh, iCANCAM cam kết xây dựng môi trường học tập cảm hứng nhất.',
    ctaTitle: 'Sẵn Sàng Cùng iCANCAM Làm Chủ Tiếng Anh?',
    ctaDesc: 'Hãy để con bạn trải nghiệm mô hình giáo dục hiện đại, kích hoạt khả năng tự học độc lập và tự tin giao tiếp ngay hôm nay.',
    ctaPrimaryBtn: 'Đăng Ký Tư Vấn Ngay',
    ctaSecondaryBtn: 'Xem Chương Trình Học',
  },
  curriculum: {
    heroBadge: 'LỘ TRÌNH ĐÀO TẠO CHUẨN QUỐC TẾ',
    heroTitle: 'Chương\u00A0Trình Đào\u00A0Tạo iCANCAM',
    heroSubtitle: 'Lộ trình học tối ưu kết hợp mô hình 4Ls + LETI và công nghệ 21st, giúp học viên phát triển toàn diện 4 kỹ năng và khả năng tự\u00A0học độc\u00A0lập suốt đời.',
    filterAll: 'Tất Cả Chương Trình',
    filterKids: 'Trẻ Em & Mầm Non (4-11t)',
    filterTeens: 'Thiếu Niên (12-15t)',
    filterIelts: 'Luyện Thi IELTS',
    filterComm: 'Giao Tiếp Thực Chiến',
    filterOnline: 'iCAM Online',
    durationLabel: 'Thời lượng:',
    targetGroupLabel: 'Đối tượng:',
    commitmentLabel: 'Cam kết đầu ra:',
    viewSyllabusBtn: 'Xem Chi Tiết Lộ Trình',
    registerBtn: 'Đăng Ký Tư Vấn',
    whyTag: 'ƯU ĐIỂM VƯỢT TRỘI',
    whyTitle: 'Tại Sao Lộ Trình Đào Tạo Tại iCANCAM Hiệu Quả?',
    whyCard1Title: 'Mô Hình 4Ls + LETI Tương Tác',
    whyCard1Desc: 'Kết hợp 4 kỹ năng cốt lõi với phương pháp học qua tương tác hai chiều, thảo luận và hoạt động thực tế.',
    whyCard2Title: 'Lớp Học Thông Minh 21st',
    whyCard2Desc: 'Trang bị Bảng tương tác Smartboard, giáo trình Anh Quốc và ứng dụng công nghệ đa phương tiện trực quan.',
    whyCard3Title: 'Cam Kết Output Rõ Ràng',
    whyCard3Desc: 'Lộ trình từng bước cá nhân hóa, đo lường sự tiến bộ định kỳ và cam kết kết quả bằng văn bản.',
    whyCard4Title: 'Khai Mở Năng Lực Tự Học',
    whyCard4Desc: 'Giúp học sinh làm chủ phương pháp tự nghiên cứu độc lập để tự tin phát triển tri thức lâu dài.',
    modalSyllabusTitle: 'Chi Tiết Lộ Trình Đào Tạo',
    modalRegisterBtn: 'Đăng Ký Tư Vấn Khóa Học Phù Hợp',
    ctaTitle: 'Chưa Biết Khóa Học Nào Phù Hợp Với Con?',
    ctaDesc: 'Đăng ký kiểm tra trình độ Tiếng Anh miễn phí và nhận lộ trình học cá nhân hóa từ các chuyên gia iCANCAM ngay hôm nay.',
    ctaPrimaryBtn: 'Đăng Ký Test Trình Độ Miễn Phí',
    ctaSecondaryBtn: 'Hotline Tư Vấn Trực Tiếp',
  },
  contact: {
    heroBadge: 'iCANCAM — HÓC MÔN & QUẬN 12',
    heroTitle: 'Liên Hệ & Đăng Ký Tư Vấn',
    heroSubtitle: 'Đừng ngần ngại liên hệ để nhận tư vấn lộ trình học cá nhân hóa và đăng ký kiểm tra trình độ 4 kỹ năng hoàn toàn miễn phí cùng đội ngũ chuyên gia iCANCAM.',
    hotlineBadge: 'Hotline: 0909 123 456',
    hoursBadge: 'T2 - CN: 08:00 - 21:30',
    campusTitle: 'Trụ Sở iCANCAM',
    subTag: 'Hóc Môn & Quận 12',
    addressLabel: 'Địa chỉ chính thức:',
    hotlineLabel: 'Hotline tuyển sinh & tư vấn:',
    emailLabel: 'Email hỗ trợ:',
    mapsBtn: 'Định Vị Trên Google Maps',
    hoursTitle: 'Giờ Làm Việc Trung Tâm',
    hoursDesc: 'Thứ 2 – Chủ Nhật | 08:00 – 21:30 (Mở cửa tất cả các ngày trong tuần)',
    commitTitle: 'Cam Kết Tư Vấn',
    commitDesc: 'Tư vấn viên liên hệ hỗ trợ trong vòng 24h & Test trình độ miễn phí 100%.',
    formTitle: 'Đăng Ký Tư Vấn & Test Trình Độ',
    formDesc: 'Học viên được kiểm tra trình độ 4 kỹ năng miễn phí và nhận lộ trình học cá nhân hóa.',
    successAlert: 'Gửi thông tin thành công! Bộ phận tư vấn iCANCAM sẽ liên hệ lại với bạn trong vòng 24h làm việc.',
    fullNameLabel: 'Họ và tên *',
    phoneLabel: 'Số điện thoại *',
    emailInputLabel: 'Địa chỉ Email',
    branchLabel: 'Cơ sở đăng ký *',
    branchOpt1: 'Cơ sở Trung Mỹ Tây (344 A Tổ 13 KP 1, HCM)',
    branchOpt2: 'Cơ sở Hóc Môn & Quận 12',
    courseLabel: 'Khóa học quan tâm *',
    messageLabel: 'Lời nhắn / Yêu cầu thêm',
    submitBtn: 'Gửi Yêu Cầu Tư Vấn Ngay',
    mapTitle: 'Vị Trí Bản Đồ Trung Tâm iCANCAM',
    openAppBtn: 'Mở Ứng Dụng Google Maps Chỉ Đường',
  },
  careers: {
    heroBadge: 'GIA NHẬP ĐỘI NGŨ iCANCAM',
    heroTitlePrefix: 'Cơ Hội Nghề Nghiệp & ',
    heroTitleHighlight: 'Phát Triển Sự Nghiệp',
    heroSubtitle: 'Cùng iCANCAM kiến tạo môi trường giáo dục 21st hiện đại tại Hóc Môn & Quận 12, chắp cánh cho thế hệ trẻ tự tin làm chủ ngôn ngữ và tự học suốt đời.',
    filterAll: 'Tất Cả Vị Trí',
    filterAcademic: 'Khối Học Thuật & Giáo Viên',
    filterSales: 'Tư Vấn & Tuyển Sinh',
    filterOps: 'Vận Hành & Dịch Vụ',
    cultureTag: 'VĂN HÓA LÀM VIỆC',
    cultureTitle: 'Tại Sao Bạn NÊN Đồng Hành Cùng iCANCAM?',
    cultureCard1Title: 'Thu Nhập & Thưởng Cạnh Tranh',
    cultureCard1Desc: 'Mức lương thưởng xứng đáng theo năng lực, thưởng KPI và chất lượng giảng dạy hàng tháng/quý.',
    cultureCard2Title: 'Đào Tạo Chuyên Chức Định Kỳ',
    cultureCard2Desc: 'Tập huấn phương pháp 4Ls + LETI & kỹ năng ứng dụng công nghệ Smartboard cùng chuyên gia.',
    cultureCard3Title: 'Lộ Trình Thăng Tiến Rõ Ràng',
    cultureCard3Desc: 'Cơ hội thăng tiến lên Trưởng bộ phận, Quản lý chuyên môn & Giám đốc cơ sở theo đánh giá minh bạch.',
    cultureCard4Title: 'Môi Trường Trẻ Trung & Gắn Kết',
    cultureCard4Desc: 'Đồng nghiệp nhiệt huyết, văn hóa tôn trọng, hỗ trợ lẫn nhau cùng các hoạt động Teambuilding hàng năm.',
    deptLabel: 'Phòng ban:',
    typeLabel: 'Hình thức:',
    locLabel: 'Địa điểm:',
    viewDetailBtn: 'Xem Chi Tiết',
    applyNowBtn: 'Ứng Tuyển Ngay',
    ctaTitle: 'Chưa Tìm Thấy Vị Trí Phù Hợp Nào?',
    ctaDesc: 'Đừng ngần ngại gửi hồ sơ ứng tuyển tự do (Talent Pool) cho iCANCAM. Chúng tôi luôn mở cửa chào đón các nhân tố tài năng đồng hành lâu dài!',
    ctaSendEmailBtn: 'Gửi CV Qua Email',
    modalReqTitle: 'Yêu Cầu Công Việc',
    modalBenTitle: 'Quyền Lợi Đãi Ngộ',
    modalFormTitle: 'Form Nộp Hồ Sơ Nhanh',
    fullNameLabel: 'Họ và tên *',
    fullNamePlaceholder: 'Nhập họ và tên...',
    phoneLabel: 'Số điện thoại *',
    phonePlaceholder: 'Nhập số điện thoại...',
    emailLabel: 'Email *',
    noteLabel: 'Link CV / Ghi chú thêm',
    notePlaceholder: 'Dán link Google Drive CV hoặc ghi chú kinh nghiệm...',
    submitApplyBtn: 'Gửi Hồ Sơ Ứng Tuyển',
    successAlert: '🎉 Nộp hồ sơ thành công! Bộ phận Tuyển sinh iCANCAM sẽ liên hệ với bạn trong vòng 48h làm việc.',
  },
  faq: {
    heroBadge: 'TƯ VẤN & GIẢI ĐÁP iCANCAM',
    heroTitlePrefix: 'Giải Đáp Thắc Mắc ',
    heroTitleHighlight: 'iCANCAM',
    heroSubtitle: 'Tổng hợp câu hỏi thường gặp về phương pháp 4Ls + LETI, lộ trình cam kết đầu ra, học phí cùng thông tin tuyển sinh tại Hóc Môn & Quận 12.',
    searchPlaceholder: 'Nhập từ khóa tìm kiếm (ví dụ: IELTS, cam kết, học phí...)',
    filterAll: 'Tất Cả Câu Hỏi',
    filterMethod: 'Phương Pháp & Lớp Học',
    filterCurriculum: 'Lộ Trình & Cam Kết',
    filterTuition: 'Học Phí & Ưu Đãi',
    filterLocation: 'Cơ Sở & Lịch Học',
    noResultsTitle: 'Không tìm thấy câu hỏi phù hợp',
    noResultsDesc: 'Thử tìm kiếm với từ khóa khác hoặc gửi câu hỏi trực tiếp cho đội ngũ tư vấn iCANCAM.',
    guaranteeTag: 'CAM KẾT CHẤT LƯỢNG',
    guaranteeTitle: 'iCANCAM Đảm Bảo Rằng',
    pillar1Title: 'Tư Vấn Trực Tiếp 24/7',
    pillar1Desc: 'Chuyên viên giáo dục sẵn sàng giải đáp thắc mắc lộ trình học qua Hotline & Zalo.',
    pillar2Title: 'Cam Kết Bằng Văn Bản',
    pillar2Desc: '100% học viên đăng ký lộ trình được ký hợp đồng cam kết chất lượng đầu ra.',
    pillar3Title: 'Học Độc Lập Bền Vững',
    pillar3Desc: 'Rèn luyện tư duy tự nghiên cứu giúp học sinh làm chủ tiếng Anh suốt đời.',
    ctaTitle: 'Bạn Cần Thêm Thông Tin Từ iCANCAM?',
    ctaDesc: 'Đừng ngần ngại gửi câu hỏi cho iCANCAM. Đội ngũ chuyên viên tư vấn tại Hóc Môn & Quận 12 sẽ liên hệ hỗ trợ bạn nhanh nhất.',
    ctaPrimaryBtn: 'Đăng Ký Tư Vấn Miễn Phí',
    ctaSecondaryBtn: 'Hotline: 0909 123 456',
  },
  news: {
    heroBadge: 'TIN TỨC & SỰ KIỆN iCANCAM',
    heroTitlePrefix: 'Cập Nhật Tin Tức & ',
    heroTitleHighlight: 'Sự Kiện Nổi Bật',
    heroSubtitle: 'Theo dõi các hoạt động giáo dục, đấu trường trí tuệ, thông tin học bổng cùng cẩm nang nuôi dạy con thời đại số từ iCANCAM.',
    filterAll: 'Tất Cả Tin Tức',
    filterEvents: 'Sự Kiện & Đấu Trường',
    filterScholarship: 'Chương Trình Học Bổng',
    filterTips: 'Cẩm Nang Phụ Huynh',
    latestTag: 'MỚI NHẤT',
    readMoreBtn: 'Đọc Chi Tiết Bài Viết',
    gridTag: 'DANH SÁCH BÀI VIẾT',
    gridTitle: 'Tin Tức Giáo Dục & Hoạt Động Mới Nhất',
    readCardBtn: 'Đọc bài viết',
    newsletterTitle: 'Nhận Bản Tin Giáo Dục & Thông Tin Học Bổng',
    newsletterDesc: 'Đăng ký email để không bỏ lỡ các kỳ thi đấu trường trí tuệ, cơ hội học bổng và bí quyết học giỏi tiếng Anh từ iCANCAM.',
    newsletterSuccess: 'Đăng ký thành công! Cảm ơn bạn đã đăng ký nhận bản tin iCANCAM.',
    newsletterInputPlaceholder: 'Nhập email của bạn...',
    newsletterSubmitBtn: 'Đăng Ký',
    modalCourseConsultBtn: 'Đăng Ký Tư Vấn Khóa Học',
  },
  notFound: {
    title: 'Không tìm thấy trang',
    subtitle: 'Đường dẫn bạn truy cập không tồn tại hoặc đã được chuyển sang địa chỉ khác. Vui lòng quay lại Trang chủ.',
    backHomeBtn: 'Quay lại Trang chủ',
  },
};

